server:
  port: 8080

spring:
  application:
    name: ecommerce-api
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/ecommerce_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    ignore-migration-patterns: "*:missing"

  data:
    redis:
      host: 127.0.0.1
      port: 6379

app:
  jwt:
    secret: "${JWT_SECRET:replace-this-secret-with-a-long-random-value-for-real-projects}"
    expiration-minutes: "${JWT_EXPIRATION_MINUTES:60}"
  cloudinary:
    cloud-name: "${CLOUDINARY_CLOUD_NAME}"
    api-key: "${CLOUDINARY_API_KEY}"
    api-secret: "${CLOUDINARY_API_SECRET}"
    folder: "ecommerce/products"

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

management:
  endpoints:
    web:
      base-path: /api
  endpoint:
    health:
      show-details: always
